config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :skills

  map.resources :locations

  map.resources :qualifications

  map.resources :locations

  map.resources :qualifications

  map.resources :users, :member => {:download_file => :get}, :collection => {:search => :get}

  map.root :controller => "users", :action => "index"

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :qualification
  belongs_to :preferred_location, :class_name => "Location"
  belongs_to :current_location, :class_name => "Location"
  has_one :attachment, :as => :attachable, :dependent => :destroy
  has_and_belongs_to_many :skills

  validates_presence_of :name
  
  def preferred_location_name
    self.preferred_location.name rescue "-"
  end

  def current_location_name
    self.current_location.name rescue "-"
  end

  def qualification_name
    self.qualification.name rescue "-"
  end

  def self.search(query)
    User.all(:conditions => ["users.name like ? or email like ? or phone_number like ? or  organization like ? or designation like ? or qualifications.name like ? or locations.name like ? or passport_number like ? or pan_number like ?", "%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%"],
    :include => [:qualification, :preferred_location, :current_location]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  layout "application"
  def index
    @users = User.all(:order => "name").paginate(:per_page => @@per_page, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    if params[:commit] == "Create"
      @user = User.new(params[:user])
      if params[:attachable] && params[:attachable][:uploaded_data]
        @user.attachment = Attachment.create(params[:attachable])
      end
      respond_to do |format|
        if @user.save
          format.html { redirect_to(@user, :notice => 'User was successfully created.') }
          format.xml  { render :xml => @user, :status => :created, :location => @user }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to users_url
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    if  params[:commit] == "Update"
      @user = User.find(params[:id])
      if params[:attachable] && params[:attachable][:uploaded_data]
        @user.attachment = Attachment.create(params[:attachable])
      end
      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to users_url
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  def download_file
    @user = User.find(params[:id])
    if @user.attachment
      send_file(RAILS_ROOT + "/public" + @user.attachment.public_filename)
    end
  end

  def search
    @users = User.search(params[:query]).paginate(:per_page => @@per_page, :page => params[:page])
    render :action => "index"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<table style="padding:20px">
  <tr>
    <td width="30%" class="ali_rt">Name : </td>
    <td width="60%"><%= f.text_field :name %></td>
  </tr>
  <tr>
    <td class="ali_rt">Email : </td>
    <td><%= f.text_field :email %></td>
  </tr>
  <tr>
    <td class="ali_rt">Phone : </td>
    <td><%= f.text_field :phone_number %></td>
  </tr>
  <tr>
    <td class="ali_rt">organization : </td>
    <td><%= f.text_field :organization %></td>
  </tr>
  <tr>
    <td class="ali_rt">Designation : </td>
    <td><%= f.text_field :designation %></td>
  </tr>
  <tr>
    <td class="ali_rt">Current Organization : </td>
    <td><%= f.text_field :current_organization %></td>
  </tr>
  <tr>
    <td class="ali_rt">Total Experience : </td>
    <td><%= f.text_field :total_experience %></td>
  </tr>
  <tr>
    <td class="ali_rt">Relevant Experience : </td>
    <td><%= f.text_field :relevant_experience %></td>
  </tr>
  <tr>
    <td class="ali_rt">Current CTC : </td>
    <td><%= f.text_field :current_ctc %></td>
  </tr>
  <tr>
    <td class="ali_rt">Expected CTC : </td>
    <td><%= f.text_field :expected_ctc %></td>
  </tr>
  <tr>
    <td class="ali_rt">Notice Period : </td>
    <td><%= f.text_field :notice_period %></td>
  </tr>
  <tr>
    <td class="ali_rt">Permanent/Contract : </td>
    <td><%= select :user, :employee_type, ["Permanent", "Contract"], {:selected=>@user.employee_type}, :class=>"width_250" %>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Year of Passout : </td>
    <td><%= select :user, :year_of_passout, (1940..Date.today.year).to_a, {:selected=>(@user.year_of_passout || Date.today.year)}, :class=>"width_250" %>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">DOB : </td>
    <td>
      <input type="text" name="user[date_of_birth]" size="30" autofill="false" onselect="new CalendarDateSelect( this, {year_range:10} );" onclick="new CalendarDateSelect( this, {year_range:10} );" value="<% @user.date_of_birth || Date.today %>"/>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Qualification : </td>
    <td>
      <%= select_tag "user[qualification_id]", "<option> -- </option>" + options_from_collection_for_select(Qualification.all, :id, :name, @user.qualification_id), {:class=> "width_250"} %>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Skills : </td>
    <td>    
      <%= select_tag("user[skill_ids]", options_for_select(Skill.all.collect { |cat| [cat.name, cat.id] }, @user.skills.collect { |cat| cat.id}), {:multiple=>true, :size=>6, :class=> "width_250"})%>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Current Location : </td>
    <td><%= select_tag "user[current_location_id]", "<option> -- </option>" + options_from_collection_for_select(Location.all, :id, :name, @user.current_location_id), {:class=> "width_250"} %>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Preferred Location : </td>
    <td>
      <%= select_tag "user[preferred_location_id]", "<option> -- </option>" + options_from_collection_for_select(Location.all, :id, :name, @user.preferred_location_id), {:class=> "width_250"} %>
    </td>
  </tr>
  <tr>
    <td class="ali_rt">Passport number : </td>
    <td><%= f.text_field :passport_number %></td>
  </tr>
  <tr>
    <td class="ali_rt">Pan number : </td>
    <td><%= f.text_field :pan_number %></td>
  </tr>
  <tr>
    <td class="ali_rt">Resume : </td>
    <td><%= file_field :attachable, :uploaded_data %></td>
  </tr>
  <tr>
    <td colspan="2" align="center">
      &nbsp;
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center">      
      <%= f.submit 'Cancel', :class=> "create_btn" %>
      <% if controller.action_name == "create" || controller.action_name == "new" %>
        <%= f.submit 'Create', :class=> "create_btn" %>
      <% else %>
        <%= f.submit 'Update', :class=> "create_btn" %>
      <% end %>
    </td>
  </tr>
</table>

app/views/users/edit.html.erb
<div>
  <h3><strong>Editing user</strong></h3>
  <div class="create_new"><%= link_to 'Show', @user %> | <%= link_to 'Back', users_path %></div>
</div>
<div class="clear"></div>


<% form_for(@user, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/users/index.html.erb
<div class="contentarea">
  <div>
    <h3><strong>Employees</strong></h3>
    <div class="create_new"><%= link_to image_tag('/images/edit.png', :title => "View"), new_user_path %></div>
  </div>
  <div class="clear"></div>
  <div class="content">
    <table class="emp_list">
      <thead>
        <tr>
          <td width="20%">Name</td>
          <td width="3%">Qualification</td>
          <td width="20%">Email</td>
          <td width="20%">Phone</td>
          <td width="20%">organization</td>
          <td width="16%">Options</td>
        </tr>
      </thead>
      <tbody>
        <% @users.each_with_index do |user, index| %>
          <tr class="row<%= index % 2 %>">
            <td><%= user.name %></td>
            <td><%= user.qualification_name %></td>
            <td><%= user.email %></td>
            <td><%= user.phone_number %></td>
            <td><%= user.organization %></td>
            <td>
              &nbsp;&nbsp;<%= link_to image_tag('/images/view.png', :title => "View"), user %> &nbsp;&nbsp;
              <%= link_to image_tag('/images/edit.png', :title => "Edit"), edit_user_path(user) %> &nbsp;&nbsp;
              <%= link_to image_tag('/images/delete.png', :title => "Delete"), user, :confirm => 'Are you sure?', :method => :delete %>
            <% if user.attachment %>
              &nbsp;&nbsp;<%= link_to image_tag('/images/document-export.png', :title => "Download"), download_file_user_path(user) %> &nbsp;&nbsp; <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div style="padding: 10px"></div>
    <%= will_paginate @users, :query => params[:query] %>
  </div>
</div>

app/views/users/new.html.erb
<div class="content">
  <h1>New user</h1>

  <% form_for(@user, :html => {:multipart => true}) do |f| %>
    <%= f.error_messages %>
    <%= render :partial => "form", :locals => {:f => f} %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="contentarea">
  <div>
    <h3><strong></strong></h3>
    <div class="create_new"><%= link_to 'Edit', edit_user_path(@user) %> | <%= link_to 'Back', users_path %></div>
  </div>
  <div class="clear"></div>
  <div class="content">
    <table class="emp_list">
      <thead>
        <tr>
          <td width="20%"><strong><%= @user.name %></strong></td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Email</td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td><%= @user.phone_number %></td>
        </tr>
        <tr>
          <td>organization</td>
          <td><%= @user.organization %></td>
        </tr>
        <tr>
          <td>Designation</td>
          <td><%= @user.designation %></td>
        </tr>
        <tr>
          <td>Current Organization</td>
          <td><%= @user.current_organization %></td>
        </tr>
        <tr>
          <td>Total Experience</td>
          <td><%= @user.total_experience %></td>
        </tr>
        <tr>
          <td>Relevant Experience</td>
          <td><%= @user.relevant_experience %></td>
        </tr>
        <tr>
          <td>Current CTC</td>
          <td><%= @user.current_ctc %></td>
        </tr>
        <tr>
          <td>Expected CTC</td>
          <td><%= @user.expected_ctc %></td>
        </tr>
        <tr>
          <td>Notice Period</td>
          <td><%= @user.notice_period %></td>
        </tr>
        <tr>
          <td>Permanent/Contract</td>
          <td><%= @user.employee_type %>
          </td>
        </tr>
        <tr>
          <td>Year of Passout </td>
          <td><%=@user.year_of_passout %>
          </td>
        </tr>
        <tr>
          <td>DOB</td>
          <td><%= display_date(@user.date_of_birth) %></td>
        </tr>
        <tr>
          <td>Qualification</td>
          <td>
            <%= @user.qualification_name %>
          </td>
        </tr>
        <tr>
          <td>Skills</td>
          <td>
            <%= @user.skills.collect{|x| x.name}.join(", ") %>
          </td>
        </tr>
        <tr>
          <td>Current Location</td>
          <td><%= @user.current_location_name%>
          </td>
        </tr>
        <tr>
          <td>Preferred Location</td>
          <td>
            <%= @user.preferred_location_name %>
          </td>
        </tr>
        <tr>
          <td>Passport number</td>
          <td><%= @user.passport_number %></td>
        </tr>
        <tr>
          <td>Pan number</td>
          <td><%= @user.pan_number %></td>
        </tr>
        <tr>
          <td>Resume</td>
          <td><%= link_to(@user.attachment.filename, download_file_user_path(@user)) rescue "-"%></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>